### PR TITLE
Relay UX fixes

### LINKED ISSUE #44: View-only on access control pages when not signed into proper role

### LINKED ISSUE #46: Search bar should be functional or removed temporarily

### PR DESCRIPTION
**Pull request by awantoch**
Closes #46 #47

Partially closes #44 -- repo metadata fields are disabled when not orgAdmin, however for the org-level, we simply hide the "Manage Access / View All" button from the sidebar when not a proper role. We could create a separate page, similar to "Activity" that just renders all of the org admins & repo devs in a simple list, without any of the advanced mechanisms. Or, we can continue with creating a "read only" version of the edit page that disables/hides relevant buttons and fields. This is a quick and dirty solution for now though.

### CODE REVIEW

File: relay/components/Navigation/NavBar.tsx [hunk 1]
```diff
@@ -77,9 +42,35 @@ export const Nav = () => {
                   </a>
                 </nav>
               </div>
-              <div className="px-12 lg:px-0">
-
-                <div className="max-w-xs mx-auto w-full lg:max-w-md">
+              {/* @TODO figure out a way to right align login button without dynamic js below, and without breaking
```
Comment (nasdf) [inline relay/components/Navigation/NavBar.tsx:45]: I think `float-right` might work here.

**Review by nasdf — APPROVED** [review]
LGTM

File: relay/components/Navigation/NavBar.tsx (hunk 1 above)
Comment (awantoch) [reply relay/components/Navigation/NavBar.tsx:45]: ahh indeed, unfortunately already tried that one, `right-0` and a few others, it seems that the parent flex & grid elements are overriding that.

This is what it ends up looking like:

image
